export const PROMPT_API_CALL = {
    GET_REQUEST: "PROMPT_REQUEST",
    GET_SUCCESS: "PROMPT_SUCCESS",
    GET_FAILURE: "PROMPT_FAILURE",
  };
  
  export const PROMPT_REDUCER = {
    CLEAR_REDUCER: "CLEAR_REDUCER"
  }